export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_PAGE_IS_VISIBLE = 'USER_PAGE_IS_VISIBLE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const GET_TASK_GROUPS = 'GET_TASK_GROUPS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

export const GET_ACTIVE_GROUP_TASKS = 'GET_ACTIVE_GROUP_TASKS';
export const GET_ACTIVE_TASK = 'GET_ACTIVE_TASK';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';

export const TASK_DONE_SUCCESS = 'TASK_DONE_SUCCESS';


