export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const GET_TASK_GROUPS = 'GET_TASK_GROUPS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAIL = 'GET_TASKS_FAIL';

export const GET_ACTIVE_GROUP_TASKS = 'GET_ACTIVE_GROUP_TASKS';
export const GET_ACTIVE_TASK = 'GET_ACTIVE_TASK';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';

export const TASK_DONE_REQUEST = 'TASK_DONE_REQUEST';
export const TASK_DONE_SUCCESS = 'TASK_DONE_SUCCESS';
export const TASK_DONE_FAIL = 'TASK_DONE_FAIL';

export const ADD_USER_INFO_REQUEST = 'ADD_USER_INFO_REQUEST';
export const ADD_USER_INFO_SUCCESS = 'ADD_USER_INFO_SUCCESS';
export const ADD_USER_INFO_FAIL = 'ADD_USER_INFO_FAIL';

export const NEW_USER_INFO_REQUEST = 'NEW_USER_INFO_REQUEST';
export const NEW_USER_INFO_SUCCESS = 'NEW_USER_INFO_SUCCESS';
export const NEW_USER_INFO_FAIL = 'NEW_USER_INFO_FAIL';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';




